spring:
  application:
    name: ipub-common-service-test
  datasource:
    url: jdbc:oracle:thin:@192.168.139.233:1521:orcl
    username: ipub
    password: Zhouwen0510
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver

mybatis-plus:
  mapper-locations: classpath:/mappers/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.ipub: info
